version: '3.1'

services:
  billete_pg:
    image: postgres:15.1
    container_name: billete_pg
    restart: always
    environment:
      POSTGRES_DB: billete
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
